// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

namespace api.Migrations
{
    [DbContext(typeof(GameContext))]
    [Migration("20210117025831_DataSeeding")]
    partial class DataSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("GamePlayer", b =>
                {
                    b.Property<int>("GamesGameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayersPlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GamesGameId", "PlayersPlayerId");

                    b.HasIndex("PlayersPlayerId");

                    b.ToTable("GamePlayer");
                });

            modelBuilder.Entity("api.Models.Board", b =>
                {
                    b.Property<int>("BoardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CellId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Key")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BoardId");

                    b.HasIndex("CellId");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("Board");

                    b.HasData(
                        new
                        {
                            BoardId = 1,
                            GameId = 0,
                            Key = new Guid("126963f9-ff87-46c3-a4de-035177574f47"),
                            PlayerId = 1
                        },
                        new
                        {
                            BoardId = 2,
                            GameId = 0,
                            Key = new Guid("226363f9-ff87-46c3-a4de-035177574f47"),
                            PlayerId = 2
                        });
                });

            modelBuilder.Entity("api.Models.BoardCell", b =>
                {
                    b.Property<int>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CellId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BoardId", "CellId");

                    b.HasIndex("CellId");

                    b.ToTable("BoardCells");

                    b.HasData(
                        new
                        {
                            BoardId = 1,
                            CellId = 1
                        },
                        new
                        {
                            BoardId = 1,
                            CellId = 2
                        },
                        new
                        {
                            BoardId = 1,
                            CellId = 3
                        },
                        new
                        {
                            BoardId = 1,
                            CellId = 4
                        },
                        new
                        {
                            BoardId = 1,
                            CellId = 5
                        },
                        new
                        {
                            BoardId = 1,
                            CellId = 6
                        },
                        new
                        {
                            BoardId = 1,
                            CellId = 7
                        },
                        new
                        {
                            BoardId = 1,
                            CellId = 8
                        },
                        new
                        {
                            BoardId = 1,
                            CellId = 9
                        },
                        new
                        {
                            BoardId = 2,
                            CellId = 5
                        },
                        new
                        {
                            BoardId = 2,
                            CellId = 6
                        },
                        new
                        {
                            BoardId = 2,
                            CellId = 7
                        },
                        new
                        {
                            BoardId = 2,
                            CellId = 8
                        },
                        new
                        {
                            BoardId = 2,
                            CellId = 9
                        },
                        new
                        {
                            BoardId = 2,
                            CellId = 10
                        },
                        new
                        {
                            BoardId = 2,
                            CellId = 11
                        },
                        new
                        {
                            BoardId = 2,
                            CellId = 13
                        },
                        new
                        {
                            BoardId = 2,
                            CellId = 14
                        });
                });

            modelBuilder.Entity("api.Models.Cell", b =>
                {
                    b.Property<int>("CellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Key")
                        .HasColumnType("TEXT");

                    b.HasKey("CellId");

                    b.ToTable("Cells");

                    b.HasData(
                        new
                        {
                            CellId = 1,
                            ImageUrl = "https://media.nature.com/lw800/magazine-assets/d41586-020-01430-5/d41586-020-01430-5_17977552.jpg",
                            Key = new Guid("14943241-3721-4abf-8977-36290b0437ec")
                        },
                        new
                        {
                            CellId = 2,
                            ImageUrl = "https://blog.consumerguide.com/wp-content/uploads/sites/2/2018/04/Honda-N-Box.png",
                            Key = new Guid("44777ac2-8f97-4f97-9f33-95c245151fb3")
                        },
                        new
                        {
                            CellId = 3,
                            ImageUrl = "https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/paulo-bent-ply-leather-chair-o-1582926567.jpg",
                            Key = new Guid("12248303-2ec4-4afc-b6a8-8d1498c6601e")
                        },
                        new
                        {
                            CellId = 4,
                            ImageUrl = "https://static.independent.co.uk/s3fs-public/thumbnails/image/2015/10/07/23/web-ali-g-getty.jpg?width=1200",
                            Key = new Guid("ef1a7514-74e1-45b8-89ff-1495c24fc169")
                        },
                        new
                        {
                            CellId = 5,
                            ImageUrl = "https://www.sportsnet.ca/wp-content/uploads/2020/08/Lionel-Messi-Barcelona-Champions-League-1040x572.jpg",
                            Key = new Guid("82696bf9-ff87-46c3-a4de-035177574f47")
                        },
                        new
                        {
                            CellId = 6,
                            ImageUrl = "https://mk0mexiconewsdam2uje.kinstacdn.com/wp-content/uploads/2015/12/quetzal-flying-mejor.jpg",
                            Key = new Guid("12d52cf2-bf5f-414c-99f8-ab0364324557")
                        },
                        new
                        {
                            CellId = 7,
                            ImageUrl = "https://static01.nyt.com/images/2020/09/25/sports/25soccer-nationalWEB1/merlin_177451008_91c7b66d-3c8a-4963-896e-54280f374b6d-articleLarge.jpg?quality=75&auto=webp&disable=upscale",
                            Key = new Guid("06075c76-4361-4dd5-93eb-a80a28d7ab65")
                        },
                        new
                        {
                            CellId = 8,
                            ImageUrl = "https://cdn.theathletic.com/app/uploads/2019/09/06104502/GettyImages-1165481703-e1567781166557-1024x684.jpg",
                            Key = new Guid("3400c172-faa7-4e73-894c-dfa68e2e27b9")
                        },
                        new
                        {
                            CellId = 9,
                            ImageUrl = "https://cdn.vox-cdn.com/thumbor/1mxkqqttp-h6NTQ9fF6wbcXMcdg=/12x0:4907x3263/1400x1050/filters:focal(12x0:4907x3263):format(jpeg)/cdn.vox-cdn.com/uploads/chorus_image/image/49388585/16071828377_85109fdee4_o.0.0.jpg",
                            Key = new Guid("261c7359-7b71-4a24-a5eb-9e35b62cb823")
                        },
                        new
                        {
                            CellId = 10,
                            ImageUrl = "https://post.healthline.com/wp-content/uploads/2019/04/Weed_Orange_1200x628-facebook.jpg",
                            Key = new Guid("f39c648e-04c7-4c5a-a31a-6cf544a9f9d1")
                        },
                        new
                        {
                            CellId = 11,
                            ImageUrl = "https://www.motortrend.com/uploads/sites/5/2020/01/2020-Acura-NSX-front-three-quarters.jpg",
                            Key = new Guid("4a3a3aa0-0d23-406e-8d4d-82fac76066eb")
                        },
                        new
                        {
                            CellId = 12,
                            ImageUrl = "https://cottagelife.com/wp-content/uploads/2019/12/zebra-foal.jpeg",
                            Key = new Guid("2400c172-0d23-406e-8d4d-82fac76066eb")
                        },
                        new
                        {
                            CellId = 13,
                            ImageUrl = "https://cdn.shopify.com/s/files/1/0550/6737/products/ORANGEWOOD_ECHO_SPRUCE_SOLID_TOP_DREADNAUGHT_ACOUSTIC_GUITAR-2_1200x.png?v=1604963852",
                            Key = new Guid("33248303-0d23-406e-8d4d-82fac76066eb")
                        },
                        new
                        {
                            CellId = 14,
                            ImageUrl = "https://media.architecturaldigest.com/photos/55f9e3f09bff6eeb3a244061/master/w_1600%2Cc_limit/dam-images-shopping-2014-07-bicycles-01-martone.jpg",
                            Key = new Guid("99943241-0d23-406e-8d4d-82fac76066eb")
                        });
                });

            modelBuilder.Entity("api.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Key")
                        .HasColumnType("TEXT");

                    b.HasKey("GameId");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            Key = new Guid("5d516a2b-9722-481c-b98e-89831ae4a732")
                        });
                });

            modelBuilder.Entity("api.Models.GamePlayerBoard", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId", "PlayerId", "BoardId");

                    b.HasIndex("BoardId");

                    b.HasIndex("PlayerId");

                    b.ToTable("GamePlayerBoard");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            PlayerId = 1,
                            BoardId = 1
                        },
                        new
                        {
                            GameId = 1,
                            PlayerId = 2,
                            BoardId = 2
                        });
                });

            modelBuilder.Entity("api.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            FirstName = "Nelson",
                            Key = new Guid("5d516a2b-9722-481c-b98e-89831ae4a732"),
                            LastName = "Samayoa"
                        },
                        new
                        {
                            PlayerId = 2,
                            FirstName = "Bayron",
                            Key = new Guid("5d526a2b-9722-481c-b98e-89831ae4a732"),
                            LastName = "Pineda"
                        });
                });

            modelBuilder.Entity("GamePlayer", b =>
                {
                    b.HasOne("api.Models.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayersPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("api.Models.Board", b =>
                {
                    b.HasOne("api.Models.Cell", null)
                        .WithMany("Boards")
                        .HasForeignKey("CellId");

                    b.HasOne("api.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Player", "Player")
                        .WithOne("Board")
                        .HasForeignKey("api.Models.Board", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("api.Models.BoardCell", b =>
                {
                    b.HasOne("api.Models.Board", "Board")
                        .WithMany("BoardCells")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Cell", "Cell")
                        .WithMany("BoardCells")
                        .HasForeignKey("CellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("Cell");
                });

            modelBuilder.Entity("api.Models.GamePlayerBoard", b =>
                {
                    b.HasOne("api.Models.Board", "Board")
                        .WithMany("GamePlayerBoards")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Game", "Game")
                        .WithMany("GamePlayerBoards")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.Player", "Player")
                        .WithMany("GamePlayerBoards")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("api.Models.Board", b =>
                {
                    b.Navigation("BoardCells");

                    b.Navigation("GamePlayerBoards");
                });

            modelBuilder.Entity("api.Models.Cell", b =>
                {
                    b.Navigation("BoardCells");

                    b.Navigation("Boards");
                });

            modelBuilder.Entity("api.Models.Game", b =>
                {
                    b.Navigation("GamePlayerBoards");
                });

            modelBuilder.Entity("api.Models.Player", b =>
                {
                    b.Navigation("Board");

                    b.Navigation("GamePlayerBoards");
                });
#pragma warning restore 612, 618
        }
    }
}
